### ISSUE TITLE
Can't use the datepicker

### ISSUE THREAD

**Issue by Kotuhan** [trendmicro-frontend/react-datepicker#2]
Here is what I got on the console when trying to include Datepicker inside the project

![screen shot 2017-12-15 at 3 07 24 pm](https://user-images.githubusercontent.com/15195110/34099127-4e421d66-e3e7-11e7-9c25-dd455537033f.png)

**Comment by cheton** [comment]
Hi @Kotuhan 

React v16 has dropped support for `React.PropTypes`, and "react-flex" (also maintained by **zippy-ui**) has to be updated to use `prop-types` package. It appears that **zippy-ui** will not maintain their packages any longer. Could you temporarily roll back React to v15? Thanks.

I will rewrite the code to cut off zippy-ui dependencies.

**Comment by Kotuhan** [comment]
Hi, @cheton!
Ok, thanks! Rolled back to v15 and have few issues:

- Broken styles
- Need to pass props to customize buttons and weekDays visibility
- it doesn't trigger "expanded" by itself. Not a big problem to handle expanded state outside, but...

![screen shot 2017-12-18 at 5 17 59 pm](https://user-images.githubusercontent.com/15195110/34113100-493f5f56-e417-11e7-81c0-a1be09a4260e.png)

**Comment by cheton** [comment]
@Kotuhan 

You cannot use DateInput to trigger the DatePicker. Instead, you have to use DateInput and DatePicker components separately in your render function, as shown in **react-datepicker**'s examples:

https://github.com/trendmicro-frontend/react-datepicker/blob/master/examples/DateTimeRangePicker/DateTimeRangePicker.jsx#L51-L80

**Comment by cheton** [comment]
![image](https://user-images.githubusercontent.com/447801/34115388-73dd51b2-e450-11e7-8827-885d2c3ab3b1.png)

**Comment by Kotuhan** [comment]
@cheton Oh, ok, thanks!
